NAME = FragTrap

SRC = main.cpp ClapTrap.cpp FragTrap.cpp

CC = -c++ -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(SRC)
	$(CC) $(SRC) -o $(NAME)

clean:
	rm -rf $(NAME)

fclean: clean

re: fclean all